[project]
name = "docktuna"
version = "0.1.0"
description = "Tools for a using Optuna with RDB storage in a fully containerized environment"
authors = ["Duane Goodner <dmgoodner@gmail.com>"]
dependencies = [
    'black>=25.1.0,<26.0.0',
    'dotenv>=0.9.9,<1.0.0',
    'isort>=6.0.1,<7.0.0',
    'optuna>=4.2.1,<5.0.0',
    'psycopg2>=2.9.10,<3.0.0',
    'numpy2.1.3',
    'torch>=2.6.0,<3.0.0',
    'torchvision>=0.21.0,<1.0.0',
    'torchview>=0.2.6,<1.0.0',
]

[project.optional-dependencies]
dev = [
    'pytest>=8.3.5,<9.0.0',
    'coverage>=7.6.12,<8.0.0',
    'pytest-cov>=6.0.0,<7.0.0',
]

[build-system]
requires = [
    'setuptools',
    'wheel',
]
build-backend = "setuptools.build_meta"
