
[tool.poetry]
name = "docktuna"
version = "0.1.0"
description = "Tools for a using Optuna with RDB storage in a fully containerized environment"
authors = ["Duane Goodner <dmgoodner@gmail.com>"]
license = "MIT"
include = ["license"]
packages = [{include = "docktuna", from = "src"}]
package-mode = true

[tool.poetry.dependencies]
python = "^3.11"
black = "^25.1.0"
dotenv = "^0.9.9"
isort = "^6.0.1"
optuna = "^4.2.1"
psycopg2 = "^2.9.10"
numpy = "2.1.3"
torch = "^2.6.0"
torchvision = "^0.21.0"
torchview = "^0.2.6"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
coverage = "^7.6.12"
pytest-cov = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = "src"
addopts = "--cov=src/docktuna --cov-branch --cov-report term --cov-report xml"

[tool.coverage.xml]
output = "coverage.xml"

[tool.black]
line-length = 79

